<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>CDX Login Database error</title>
    <link rel="stylesheet" type="text/css" href="main.css" />
</head>
<body>
    <div id="page">
        <div id="header">
            <h1>CDX Login: DB error</h1>
        </div>

        <div id="main">
            <h1>Database Error</h1>
            <p>Error message: <?php echo $error_message; ?></p>
            <p>&nbsp;</p>
        </div><!-- end main -->

        <div id="footer">
            <p>
                &copy; <?php echo date("Y"); ?> 
            </p>
        </div>

    </div>
</body>
</html>